/**
 * Generate a TypeScript chapter file from extracted-sections JSON.
 *
 * Usage:
 *   npx tsx scripts/generate-chapter.ts \
 *     --extracted extracted-fundamentals.json \
 *     --translations scripts/translations-fundamentals.json \
 *     --chapter-id fundamentals \
 *     --chapter-title "Fundamentals / 围棋基础" \
 *     --out src/game/chapters/fundamentals.ts
 *
 * Each source Section becomes a "chapter" (top-level group) in go-game; each
 * Page within becomes a Level.  Pages flagged skip=true are dropped.
 */

import * as fs from "fs";
import * as path from "path";

interface ExtractedMark {
    [shape: string]: string;
}
interface ExtractedMultipleChoice {
    question: string;
    options: { value: string; label: string }[];
    correctValue: string;
    hasBoard: boolean;
}
interface ExtractedEndingGame {
    interaction: "pass" | "stoneRemoval" | "finish";
    targetRemoval?: string;
}
interface ExtractedPage {
    pageClassName: string;
    pageIndex: number;
    text: string | null;
    width: number;
    height: number;
    initialPlayer: "black" | "white" | null;
    initialState: { black: string; white: string } | null;
    marks: ExtractedMark | null;
    correct: string[];
    wrong: string[];
    multipleChoice: ExtractedMultipleChoice | null;
    endingGame: ExtractedEndingGame | null;
    skip: boolean;
    skipReason?: string;
}
interface ExtractedSection {
    sectionClassName: string;
    sectionId: string;
    title: string;
    subtext: string;
    sourceFile: string;
    pages: ExtractedPage[];
}

interface Args {
    extractedPath: string;
    translationsPath: string;
    chapterId: string;
    chapterTitle: string;
    outPath: string;
}

function parseArgs(argv: string[]): Args {
    const args: Record<string, string> = {};
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a.startsWith("--")) args[a.slice(2)] = argv[++i];
    }
    const required = ["extracted", "translations", "chapter-id", "chapter-title", "out"];
    for (const r of required) {
        if (!args[r]) {
            console.error(`Missing --${r}`);
            process.exit(1);
        }
    }
    return {
        extractedPath: args.extracted!,
        translationsPath: args.translations!,
        chapterId: args["chapter-id"]!,
        chapterTitle: args["chapter-title"]!,
        outPath: args.out!,
    };
}

/** Escape a string for embedding in TS as a double-quoted string literal. */
function str(s: string): string {
    return JSON.stringify(s);
}

/** Convert an arbitrary section id (kebab-case, possibly with trailing digits
 *  like "bl1-capturing-race-1") to a valid TS identifier. */
function toCamel(s: string): string {
    // Replace each run of non-alphanumeric with camelCase boundary.
    const parts = s.split(/[^a-zA-Z0-9]+/).filter(Boolean);
    const camel = parts
        .map((p, i) =>
            i === 0
                ? p.replace(/^(\d)/, "_$1") // leading digit -> prefix _ (rare)
                : p.charAt(0).toUpperCase() + p.slice(1),
        )
        .join("");
    return camel;
}

/** Convert "Fundamentals" / "围棋基础" -> { zh, en } LocalizedText based on chapterTitle arg. */
function splitLocale(arg: string): { zh: string; en: string } {
    // Format: "English / 中文"
    const idx = arg.indexOf("/");
    if (idx < 0) return { en: arg.trim(), zh: arg.trim() };
    return { en: arg.slice(0, idx).trim(), zh: arg.slice(idx + 1).trim() };
}

/** Map a section title to a stable, human-readable level title for each page. */
function makeLevelTitle(
    sectionTitle: string,
    sectionTitleZh: string,
    pageIndex: number,
    pageCount: number,
): { zh: string; en: string } {
    const en = pageCount > 1 ? `${sectionTitle} · ${pageIndex + 1}/${pageCount}` : sectionTitle;
    const zh = pageCount > 1 ? `${sectionTitleZh} · ${pageIndex + 1}/${pageCount}` : sectionTitleZh;
    return { zh, en };
}

function generate(args: Args): string {
    const data = JSON.parse(fs.readFileSync(args.extractedPath, "utf8")) as { sections: ExtractedSection[] };
    const translations = JSON.parse(fs.readFileSync(args.translationsPath, "utf8")) as Record<string, string>;
    // Strip the _comment key if present.
    delete (translations as Record<string, unknown>)["_comment"];

    const chapterTitle = splitLocale(args.chapterTitle);

    const lines: string[] = [];
    lines.push(`/*`);
    lines.push(` * AUTO-GENERATED by scripts/generate-chapter.ts.`);
    lines.push(` * Source: LearningHub / ${args.chapterId}`);
    lines.push(` * Do not edit by hand — regenerate from extracted JSON + translations.`);
    lines.push(` */`);
    lines.push(`import type { Chapter, Level } from "../types";`);
    lines.push(``);
    lines.push(`export const CHAPTER_ID = ${str(args.chapterId)};`);
    lines.push(``);
    lines.push(`export const CHAPTER: Chapter = {`);
    lines.push(`    id: ${str(args.chapterId)},`);
    lines.push(`    title: { zh: ${str(chapterTitle.zh)}, en: ${str(chapterTitle.en)} },`);
    lines.push(`    description: {`);
    lines.push(`        zh: ${str(chapterTitle.zh)},`);
    lines.push(`        en: ${str(chapterTitle.en)},`);
    lines.push(`    },`);
    lines.push(`};`);
    lines.push(``);

    // Counter for global ordering inside the chapter.
    let order = 0;
    const sectionsOut: { sectionVar: string; sectionTitle: string; pageCount: number }[] = [];

    for (const section of data.sections) {
        const usablePages = section.pages.filter((p) => !p.skip);
        if (usablePages.length === 0) {
            // Skip section entirely — emit a comment.
            lines.push(`/* Section ${section.sectionId} (${section.title}) had no migratable pages — skipped. */`);
            lines.push(``);
            continue;
        }

        const sectionVar = `${toCamel(section.sectionId)}Levels`;
        sectionsOut.push({
            sectionVar,
            sectionTitle: section.title,
            pageCount: usablePages.length,
        });

        lines.push(`const ${sectionVar}: Level[] = [`);

        usablePages.forEach((p, i) => {
            order++;
            const textEn = p.text ?? "";
            const textZh = translations[textEn] ?? textEn;
            const title = makeLevelTitle(
                section.title,
                translations[section.title] ?? section.title,
                i,
                usablePages.length,
            );
            const levelId = `${args.chapterId}-${section.sectionId}-${i + 1}`;

            lines.push(`    {`);
            lines.push(`        id: ${str(levelId)},`);
            lines.push(`        chapterId: ${str(args.chapterId)},`);
            lines.push(`        order: ${order},`);
            lines.push(`        title: { zh: ${str(title.zh)}, en: ${str(title.en)} },`);
            lines.push(`        instruction: { zh: ${str(textZh)}, en: ${str(textEn)} },`);
            if (p.multipleChoice) {
                lines.push(`        kind: "multipleChoice",`);
            } else if (p.endingGame) {
                lines.push(`        kind: "endingGame",`);
            }
            lines.push(`        puzzle: {`);
            lines.push(`            width: ${p.width},`);
            lines.push(`            height: ${p.height},`);
            if (p.initialPlayer) {
                lines.push(`            initial_player: ${str(p.initialPlayer)},`);
            }
            if (p.initialState) {
                lines.push(`            initial_state: { black: ${str(p.initialState.black)}, white: ${str(p.initialState.white)} },`);
            } else {
                lines.push(`            initial_state: { black: "", white: "" },`);
            }
            if (p.marks) {
                const entries = Object.entries(p.marks)
                    .map(([k, v]) => `${k}: ${str(v)}`)
                    .join(", ");
                lines.push(`            marks: { ${entries} },`);
            }
            lines.push(`            correct: [${p.correct.map(str).join(", ")}],`);
            if (p.wrong.length > 0) {
                lines.push(`            wrong: [${p.wrong.map(str).join(", ")}],`);
            }
            lines.push(`        },`);
            if (p.multipleChoice) {
                const mc = p.multipleChoice;
                const mcQuestionZh = translations[mc.question] ?? mc.question;
                const opts = mc.options
                    .map((o) => {
                        const optZh = translations[o.label] ?? o.label;
                        return `{ value: ${str(o.value)}, label: { zh: ${str(optZh)}, en: ${str(o.label)} } }`;
                    })
                    .join(", ");
                lines.push(`        multipleChoice: {`);
                lines.push(`            question: { zh: ${str(mcQuestionZh)}, en: ${str(mc.question)} },`);
                lines.push(`            options: [${opts}],`);
                lines.push(`            correctValue: ${str(mc.correctValue)},`);
                if (mc.hasBoard && p.initialState) {
                    lines.push(`            board: {`);
                    lines.push(`                width: ${p.width},`);
                    lines.push(`                height: ${p.height},`);
                    lines.push(`                initial_state: { black: ${str(p.initialState.black)}, white: ${str(p.initialState.white)} },`);
                    if (p.marks) {
                        const entries = Object.entries(p.marks)
                            .map(([k, v]) => `${k}: ${str(v)}`)
                            .join(", ");
                        lines.push(`                marks: { ${entries} },`);
                    }
                    lines.push(`            },`);
                }
                lines.push(`        },`);
            }
            if (p.endingGame) {
                const eg = p.endingGame;
                lines.push(`        endingGame: {`);
                lines.push(`            width: ${p.width},`);
                lines.push(`            height: ${p.height},`);
                if (p.initialState) {
                    lines.push(`            initial_state: { black: ${str(p.initialState.black)}, white: ${str(p.initialState.white)} },`);
                } else {
                    lines.push(`            initial_state: { black: "", white: "" },`);
                }
                if (p.marks) {
                    const entries = Object.entries(p.marks)
                        .map(([k, v]) => `${k}: ${str(v)}`)
                        .join(", ");
                    lines.push(`            marks: { ${entries} },`);
                }
                lines.push(`            interaction: ${str(eg.interaction)},`);
                if (eg.targetRemoval) {
                    lines.push(`            targetRemoval: ${str(eg.targetRemoval)},`);
                }
                lines.push(`        },`);
            }
            lines.push(`    },`);
        });

        lines.push(`];`);
        lines.push(``);
    }

    // Combine all sections in order.
    lines.push(`export const LEVELS: Level[] = [`);
    for (const s of sectionsOut) {
        lines.push(`    ...${s.sectionVar},`);
    }
    lines.push(`];`);
    lines.push(``);

    return lines.join("\n");
}

function main() {
    const args = parseArgs(process.argv.slice(2));
    const out = generate(args);
    fs.mkdirSync(path.dirname(args.outPath), { recursive: true });
    fs.writeFileSync(args.outPath, out);
    console.log(`Wrote ${args.outPath}`);
}

main();
