/*
 * AUTO-GENERATED by scripts/generate-chapter.ts.
 * Source: LearningHub / fundamentals
 * Do not edit by hand — regenerate from extracted JSON + translations.
 */
import type { Chapter, Level } from "../types";

export const CHAPTER_ID = "fundamentals";

export const CHAPTER: Chapter = {
    id: "fundamentals",
    title: { zh: "围棋基础", en: "Fundamentals" },
    description: {
        zh: "围棋基础",
        en: "Fundamentals",
    },
};

const rulesIntroLevels: Level[] = [
    {
        id: "fundamentals-rules-intro-1",
        chapterId: "fundamentals",
        order: 1,
        title: { zh: "The Game of Go · 1/6", en: "The Game of Go · 1/6" },
        instruction: { zh: "棋局从一个空棋盘开始。两位玩家，黑和白，轮流在棋盘上落子。黑棋先行。你可以在任意空交叉点落子，包括最外圈。请下一步继续。", en: "The game starts with an empty board. Two players, Black and White, take turns placing stones on the board. Black starts. You can play a stone on any empty intersection, even the outer ones. Make a move to continue." },
        puzzle: {
            width: 9,
            height: 9,
            initial_state: { black: "", white: "" },
            correct: ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", "d9", "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "g1", "g2", "g3", "g4", "g5", "g6", "g7", "g8", "g9", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9", "j1", "j2", "j3", "j4", "j5", "j6", "j7", "j8", "j9"],
        },
    },
    {
        id: "fundamentals-rules-intro-2",
        chapterId: "fundamentals",
        order: 2,
        title: { zh: "The Game of Go · 2/6", en: "The Game of Go · 2/6" },
        instruction: { zh: "黑棋已经走了第一步。现在轮到白棋。请下一步继续。", en: "Black has played the first move. Now it is White's turn. Make a move to continue." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "c3", white: "" },
            correct: ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "c1", "c2", "c4", "c5", "c6", "c7", "c8", "c9", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", "d9", "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "g1", "g2", "g3", "g4", "g5", "g6", "g7", "g8", "g9", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9", "j1", "j2", "j3", "j4", "j5", "j6", "j7", "j8", "j9"],
        },
    },
    {
        id: "fundamentals-rules-intro-3",
        chapterId: "fundamentals",
        order: 3,
        title: { zh: "The Game of Go · 3/6", en: "The Game of Go · 3/6" },
        instruction: { zh: "棋子相邻的空点叫做『气』。请填上黑子的一个气。", en: "The points next to a stone are called liberties. Fill one of the liberties of the black stone." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "c3", white: "" },
            marks: { cross: "b3d3c2c4" },
            correct: ["b3", "d3", "c2", "c4"],
        },
    },
    {
        id: "fundamentals-rules-intro-4",
        chapterId: "fundamentals",
        order: 4,
        title: { zh: "The Game of Go · 4/6", en: "The Game of Go · 4/6" },
        instruction: { zh: "当一个棋子所有的气都被对方棋子占满，它就被吃掉了。请填上黑子的最后一口气把它吃掉。", en: "A stone is captured when all its liberties are occupied by the opponent's stones. Capture the black stone by filling the last liberty of the black stone." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "c3", white: "b3c2c4" },
            marks: { cross: "d3" },
            correct: ["d3"],
        },
    },
    {
        id: "fundamentals-rules-intro-5",
        chapterId: "fundamentals",
        order: 5,
        title: { zh: "The Game of Go · 5/6", en: "The Game of Go · 5/6" },
        instruction: { zh: "同色相邻的棋子连成一气，称为『链』。请填上这条黑链的一个气。", en: "Stones of the same color next to each other form a chain. Fill one of the liberties of the black chain." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "c3c4d4", white: "" },
            marks: { cross: "b3b4c2c5d3d5e4" },
            correct: ["b3", "b4", "c2", "c5", "d3", "d5", "e4"],
        },
    },
    {
        id: "fundamentals-rules-intro-6",
        chapterId: "fundamentals",
        order: 6,
        title: { zh: "The Game of Go · 6/6", en: "The Game of Go · 6/6" },
        instruction: { zh: "这条黑链只剩一气了，这叫做『打吃』（atari）。请吃掉这条被打吃的黑链。", en: "The black chain has only one liberty left. This is called 'atari'. Capture the black chain that is in atari." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "c3c4d4", white: "b3b4c2c5d3d5" },
            marks: { cross: "e4" },
            correct: ["e4"],
        },
    },
];

const selfCaptureLevels: Level[] = [
    {
        id: "fundamentals-self-capture-1",
        chapterId: "fundamentals",
        order: 7,
        title: { zh: "Self-capture · 1/3", en: "Self-capture · 1/3" },
        instruction: { zh: "白先。下在 A 或 B 是『自杀』（白没有气），不允许。但下在 C 是允许的，因为能吃掉标▲的黑子从而给自己造出气。请吃掉标▲的黑子。", en: "White to play. Playing at A or B is called 'self-capture' (no liberties for White) and is not allowed. But playing at C is allowed, because it captures the marked stones, creating liberties for White. Capture the marked black stones." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "ceeedfffegehhagbibhc", white: "eddefegffg" },
            marks: { A: "ia", B: "hb", C: "ef", triangle: "eeff" },
            correct: ["ef"],
        },
    },
    {
        id: "fundamentals-self-capture-2",
        chapterId: "fundamentals",
        order: 8,
        title: { zh: "Self-capture · 2/3", en: "Self-capture · 2/3" },
        instruction: { zh: "白先。双方都被打吃。没有气的着法不允许，除非能吃掉对方。请吃掉一颗或更多黑子。", en: "White to play. Both players are in atari. Placing a stone where you have no liberties is not allowed, unless you can capture stones. Capture one or more black stones." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "efffcgdgggehfh", white: "eefecfdfgfeg" },
            correct: ["fg"],
        },
    },
    {
        id: "fundamentals-self-capture-3",
        chapterId: "fundamentals",
        order: 9,
        title: { zh: "Self-capture · 3/3", en: "Self-capture · 3/3" },
        instruction: { zh: "白先。双方都被打吃。没有气的着法不允许，除非能吃掉对方。请吃掉一颗或更多黑子。", en: "White to play. Both players are in atari. Placing a stone where you have no liberties is not allowed, unless you can capture stones. Capture one or more black stones." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "white",
            initial_state: { black: "becfagbgchdhehciei", white: "cgdgegahbhfhbifi" },
            correct: ["di"],
        },
    },
];

const eyesLevels: Level[] = [
    {
        id: "fundamentals-eyes-1",
        chapterId: "fundamentals",
        order: 10,
        title: { zh: "Eyes · 1/4", en: "Eyes · 1/4" },
        instruction: { zh: "A 点被白子包围，这叫『眼』。黑不能下在 A（自吃）。B 点也是眼，但黑可以下在 B 并吃掉白子。请吃掉这些白子。", en: "Point A is surrounded by white stones; it is called an 'eye'. Black can not play at A (self-capture). Point B is also an eye, but Black can play at B and capture. Capture the white stones." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "c1c2c3d3e3f3g3g2g1", white: "c7d8e7d6d1d2e2f2f1" },
            marks: { A: "d7", B: "e1" },
            correct: ["e1"],
        },
    },
    {
        id: "fundamentals-eyes-2",
        chapterId: "fundamentals",
        order: 11,
        title: { zh: "Eyes · 2/4", en: "Eyes · 2/4" },
        instruction: { zh: "白棋有一个由两个空点组成的大眼，但白棋并不安全。黑先，逐一填眼吃掉白棋。", en: "White has a single bigger eye of two points, but the white group is not safe. Black to play. Capture the white stones by filling the eye point by point." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "a3b3c3d3d2d1", white: "a2b2c2c1" },
            correct: ["a1b1a1", "b1a1b1"],
        },
    },
    {
        id: "fundamentals-eyes-3",
        chapterId: "fundamentals",
        order: 12,
        title: { zh: "Eyes · 3/4", en: "Eyes · 3/4" },
        instruction: { zh: "白棋有两块棋。一块有两只眼，另一块只有一个大眼。两眼的那块是活的，永远吃不掉。黑先，吃掉那块可以吃的白棋。", en: "White has two groups of stones. One group has two eyes. The other group has a single big eye. The group with two eyes is safe and can never be captured. Black to play. Capture a white group." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "a3b3c3d3e3e2e1g9g8g7g6g5h5j5", white: "a2b2c2d2d1b1h9h8h7h6j6" },
            correct: ["j8j7j9"],
            wrong: ["j7j8", "j9j8"],
        },
    },
    {
        id: "fundamentals-eyes-4",
        chapterId: "fundamentals",
        order: 13,
        title: { zh: "Eyes · 4/4", en: "Eyes · 4/4" },
        instruction: { zh: "一块白棋有两只『真眼』。另一块在 A 处有真眼、在 B 处是『假眼』。假眼不安全，可以被攻破。黑先，从假眼入手吃掉这块白棋。", en: "One white group has two 'real' eyes. The other group has a real eye at A and a 'false' eye at B. The false eye is not safe and can be attacked. Black to play. Capture the white group by attacking the false eye." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "a3b3c3d3e3e2e1g9g8g7g6h5j5", white: "a2b2c2d2d1b1h9h8h7j8j6" },
            marks: { A: "j9", B: "j7" },
            correct: ["h6j7j9"],
        },
    },
];

const koLevels: Level[] = [
    {
        id: "fundamentals-ko-1",
        chapterId: "fundamentals",
        order: 14,
        title: { zh: "Ko · 1/5", en: "Ko · 1/5" },
        instruction: { zh: "为了避免无限互相提子，有一条特殊规则叫『劫规』：禁止立即提回同样的形状。黑可以吃掉标▲的白子，但白不能立刻提回。白必须先在别处下一手。请吃掉标▲的白子。", en: "To prevent endlessly recapturing the same space, there is a special rule called the 'Ko rule' which prevents immediately recapturing the same position. Black can capture the marked white stone. White is not allowed to recapture the black stone immediately. White has to play elsewhere first. Capture the marked stone." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "e8e6f7", white: "c7d8e7d6" },
            marks: { triangle: "e7" },
            correct: ["d7"],
        },
    },
    {
        id: "fundamentals-ko-2",
        chapterId: "fundamentals",
        order: 15,
        title: { zh: "Ko · 2/5", en: "Ko · 2/5" },
        instruction: { zh: "利用劫规吃掉这块白棋。", en: "Capture the white group by exploiting the Ko rule." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "afbfcfcgdhcidi", white: "agbgahchbi" },
            correct: ["b2d3a1"],
        },
    },
    {
        id: "fundamentals-ko-3",
        chapterId: "fundamentals",
        order: 16,
        title: { zh: "Ko · 3/5", en: "Ko · 3/5" },
        instruction: { zh: "请把你的黑子连接起来。", en: "Connect your black stones." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "ecedeedfegehfh", white: "fdcedefeefgfcgdgfg" },
            correct: ["f4c4e4"],
            wrong: ["c4b4", "g3c4"],
        },
    },
    {
        id: "fundamentals-ko-4",
        chapterId: "fundamentals",
        order: 17,
        title: { zh: "Ko · 4/5", en: "Ko · 4/5" },
        instruction: { zh: "利用劫规吃掉这两颗白子。", en: "Capture two white stones by exploiting the Ko rule." },
        puzzle: {
            width: 9,
            height: 9,
            initial_player: "black",
            initial_state: { black: "fcfdgehfggfhgh", white: "edfeefgffgeh" },
            correct: ["f4e3e5"],
            wrong: ["e3d3", "e5d5", "h5f4", "g6f4"],
        },
    },
    {
        id: "fundamentals-ko-5",
        chapterId: "fundamentals",
        order: 18,
        title: { zh: "Ko · 5/5", en: "Ko · 5/5" },
        instruction: { zh: "白刚走了 1 吃掉一颗黑子。要绕过劫规，请为黑棋找一个白必须应的地方下子，这叫做『劫材』。然后黑就能吃掉标▲的白棋。", en: "White just captured a black stone by playing 1. To move past the ko rule, find a place to play for Black where White must capture. This is called a 'ko threat'. Next, Black can capture White's marked group." },
        puzzle: {
            width: 13,
            height: 13,
            initial_player: "black",
            initial_state: { black: "bgcgchcicjbkalclbm", white: "bebfagbhaibibjak" },
            marks: { 1: "a3", triangle: "a5b4b5b6" },
            correct: ["a8a9a4a6a8"],
            wrong: ["a4", "a9a8a4a6", "c3a8a4a6", "b2a8a4a6", "c1a8a4a6", "a1a8a4a6", "c8a8a4a6"],
        },
    },
];

/* Section territory (Territory) had no migratable pages — skipped. */

/* Section ending-the-game (End of the Game) had no migratable pages — skipped. */

const theBoardLevels: Level[] = [
    {
        id: "fundamentals-the-board-1",
        chapterId: "fundamentals",
        order: 19,
        title: { zh: "The Board · 1/3", en: "The Board · 1/3" },
        instruction: { zh: "棋盘上哪里都能下，但常见的好策略是先占角、再占边、最后走中腹。请把棋子下在右上角。", en: "You can play anywhere, but a good general strategy is to focus on the corners first, then sides, then the middle. Play a stone in the upper right hand corner." },
        puzzle: {
            width: 9,
            height: 9,
            initial_state: { black: "", white: "" },
            correct: ["f9", "g9", "h9", "j9", "f8", "g8", "h8", "j8", "f7", "g7", "h7", "j7", "f6", "g6", "h6", "j6"],
        },
    },
    {
        id: "fundamentals-the-board-2",
        chapterId: "fundamentals",
        order: 20,
        title: { zh: "The Board · 2/3", en: "The Board · 2/3" },
        instruction: { zh: "围棋的棋盘大小不限，但最常见的是 9×9（建议新手从这里开始）、13×13，以及最流行的 19×19。请把棋子下在棋盘右侧（不要下在角上）。", en: "Go can be played on any size board, but the most common are 9x9 (which you should start on), 13x13, and the most popular, 19x19. Play on the right side of the board (not in a corner)." },
        puzzle: {
            width: 13,
            height: 13,
            initial_state: { black: "", white: "" },
            correct: ["k9", "l9", "m9", "n9", "k8", "l8", "m8", "n8", "k7", "l7", "m7", "n7", "k6", "l6", "m6", "n6", "k5", "l5", "m5", "n5"],
        },
    },
    {
        id: "fundamentals-the-board-3",
        chapterId: "fundamentals",
        order: 21,
        title: { zh: "The Board · 3/3", en: "The Board · 3/3" },
        instruction: { zh: "棋盘上有几个圆点，叫做『星位』。它们本身并不特别，只是用来帮助定位。请下在任意一个星位上。", en: "You will note that there are several circles on the board, these are called \"Star Points\". These are not particularly special, they are just useful for orienting yourself with the board. Play on a star point." },
        puzzle: {
            width: 19,
            height: 19,
            initial_state: { black: "", white: "" },
            correct: ["d16", "k16", "q16", "d10", "k10", "q10", "d4", "k4", "q4"],
        },
    },
];

export const LEVELS: Level[] = [
    ...rulesIntroLevels,
    ...selfCaptureLevels,
    ...eyesLevels,
    ...koLevels,
    ...theBoardLevels,
];
